# Generated by Django 5.0.6 on 2024-06-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipiee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipie',
            old_name='recipie_namee',
            new_name='recipie_img',
        ),
    ]
