# Generated by Django 5.0.6 on 2024-07-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipiee', '0003_recipie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='recipie_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
