# Generated by Django 5.0.6 on 2024-07-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipiee', '0005_department_studentid_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_adress',
            field=models.TextField(),
        ),
    ]
